package com.curso.java;
/*
 * VIDEO 84
	 --METHOD OVERLOAD
	 --ANY METHOD CAN BE OVERLOADED
	 --OFFER MORE THAT ONE OPTION TO USE OUR METHODS
	 --THE ARGUMENTS TYPE SHOULD BE DIFERENT
	 --MAY BE THE SAME AMOUNT OF ARGUMENTS
	 --IS POSSIBLE CHANGE THE ARGUMENTS ORDER
	 --THE RETURN DATA TYPE IS NOT REVISED 
	 --ONLY THE ORDER AND TYPE ID CHEKED
	 --THE ARGUMENTS CAN BE PRIMITIVE TYPE OR OBJECT   
 *  VIDEO 85
 	--
 	--
 * */
public class _014MethodOverload {

}
