package com.curso.java;
/*
 --FINAL WORD IN JAVA 
 --DONT´N AFECT VARIABLES IN JAVA, IS POSSIBLE USE IT IN METODS AND CLASS 
 USES FINAL WORD
 --IN VARIABLES: AVOID CHANGING THE VALUE STORED BY A VARIABLE 
 --THE STORED VARIABLE WITH REFERENCES, DON´T CONTAIN THE OBJECT VALUE 
 --IN METHODS: AVOID CHAGING THE DEFINITON OF A METHOD FROM A SUB-CLASS
 --IN CLASS: AVOID EXTENDS A DAUGTHER FROM THIS
 --WE CAN DEFINE AS FINAL: CLASS, METHODS, ATTRIBUTES
 --PUBLIC FINAL CLASS... : WE CAN´T CREATE DAUGTHER CLASSES OF THIS CLASS
 */
public class _017FinalPeople {
	//VARIABLES MARKED AS END
	public final int varNumber = 10;
	
	//CONSTANTS IN JAVA 
	public static final int VAR_PRIMITIVA = 15;
	
	public final void metodoFinal() {
		
	}
}

//class executeFinal extends _017FinalPeople{
//	//DON´T IS POSSIBLE CREATE DAUTHER CLASS OF CLASS HOME WITH FINAL
////	public final void metodoFinal() {
////		
////	}
//}
